#!/usr/bin/env python3
"""
Generate backend/agents/known_locations.py from the data, replacing the hand-written,
mostly-US list the planner used to recover places the router dropped.

    python db_scripts/build_known_locations.py [--min-city-events 5000]

* Regions: every first-level division in events_table (US states, Canadian provinces, Mexican
  states; canonical spellings, see backend/queries/geo_names.py) plus a short list of countries.
* Cities: city-level places (ActionGeo_Type 3 or 4) with at least --min-city-events events in the
  extract, minus GDELT geocoding artefacts that are organisations or buildings ("World Bank").
"""

from __future__ import annotations

import argparse
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "db_scripts"))
from backend.queries.geo_names import canonical_adm1  # noqa: E402
import gdelt_raw  # noqa: E402

COUNTRIES = [
    "United States", "USA", "US", "Canada", "Mexico", "Ukraine", "Gaza", "Israel", "China", "Russia",
    "UK", "France", "Germany", "Japan", "India", "Australia", "Brazil", "Europe", "Asia", "Africa", "Middle East",
]
ALIASES = ["Washington DC", "DC", "NYC", "New York City"]
# Geocoded "places" that are institutions, buildings or generic terms; as locations they would
# hijack queries about the organisation ("BlackRock earnings").
NOT_PLACES = {
    "World Bank", "Blackrock", "Department Of Education", "Columbia University", "Trump Tower",
    "Miguel Angel", "Capitol Hill", "White House", "The White House", "Hollywood", "Times Square",
    "Stanford", "Long Island",
}
NOT_PLACE_WORDS = ("University", "Department", "Bank", "Tower", "Hospital", "Airport", "College")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--min-city-events", type=int, default=5000)
    p.add_argument("--out", default=str(ROOT / "backend" / "agents" / "known_locations.py"))
    args = p.parse_args()

    with gdelt_raw._db() as conn, conn.cursor() as cur:
        cur.execute("""
            SELECT TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(ActionGeo_FullName, ',', -2), ',', 1)) AS adm1, COUNT(*) AS n
            FROM events_table WHERE ActionGeo_Type IN (2, 3, 4, 5) AND ActionGeo_FullName LIKE '%%,%%'
            GROUP BY adm1 HAVING n >= 1000
        """)
        regions = sorted({canonical_adm1(r["adm1"]) for r in cur.fetchall()} - {"Canada (general)", "Mexico (general)"})
        cur.execute("""
            SELECT SUBSTRING_INDEX(ActionGeo_FullName, ',', 1) AS city, COUNT(*) AS n
            FROM events_table WHERE ActionGeo_Type IN (3, 4)
            GROUP BY city HAVING n >= %s ORDER BY n DESC
        """, (args.min_city_events,))
        cities = []
        for r in cur.fetchall():
            name = r["city"].strip()
            if (name in NOT_PLACES or any(w in name for w in NOT_PLACE_WORDS) or name in regions
                    or not name.isascii() or name in cities):
                continue
            cities.append(name)

    def ascii_form(name):
        return "".join(c for c in unicodedata.normalize("NFKD", name) if not unicodedata.combining(c))

    # "Yucatan" typed without the accent must still find "Yucatán".
    ascii_variants = {ascii_form(r): r for r in regions if not r.isascii()}

    def fmt(names):
        return "\n".join(f"    {n!r}," for n in sorted(set(names), key=lambda x: (-len(x), x)))

    Path(args.out).write_text(f'''"""
Place names the planner recognises in a question. GENERATED by db_scripts/build_known_locations.py
from events_table ({len(regions)} first-level divisions, {len(cities)} cities with >= {args.min_city_events}
events); edit the generator, not this file.

REGIONS (divisions, countries, aliases) match case-insensitively; CITIES and names of three letters
or fewer match only as written, so "tell us" is not the US and "mobile phones" is not Mobile.
"""

import re
from typing import Optional

REGIONS = (
{fmt(regions + COUNTRIES + ALIASES)}
)

# First-level divisions only (matched in SQL through the indexed ActionGeo_ADM1 column).
DIVISIONS = (
{fmt(regions)}
)

# Unaccented spellings people type -> canonical name.
ASCII_VARIANTS = {ascii_variants!r}

CITIES = (
{fmt(cities)}
)


def _alternation(names) -> str:
    return "|".join(re.escape(n) for n in sorted(names, key=len, reverse=True))


_LONG = [n for n in (*REGIONS, *ASCII_VARIANTS) if len(n) > 3]
_SHORT = [n for n in REGIONS if len(n) <= 3]
_REGION_RE = re.compile(rf"\\b({{_alternation(_LONG)}})\\b", re.IGNORECASE)
_EXACT_RE = re.compile(rf"\\b({{_alternation(list(CITIES) + _SHORT)}})\\b")
_CANONICAL = {{**{{n.lower(): n for n in REGIONS}}, **{{a.lower(): c for a, c in ASCII_VARIANTS.items()}}}}


def find_known_location(text: str) -> Optional[str]:
    """The first known place in ``text`` (longest name wins at a position), canonical spelling."""
    hits = [m for m in (_REGION_RE.search(text or ""), _EXACT_RE.search(text or "")) if m]
    if not hits:
        return None
    m = min(hits, key=lambda m: (m.start(), -len(m.group(1))))
    return _CANONICAL.get(m.group(1).lower(), m.group(1))
''')
    print(f"wrote {args.out}: {len(regions)} regions, {len(cities)} cities")
    return 0


if __name__ == "__main__":
    sys.exit(main())
