"""
GDELT Planner + Report Generator

Planner: router (Claude by default, local Ollama qwen2.5:3b as fallback) + deterministic checks +
rule-based fast path + remote LLM tool execution.
Report Generator: Summarizes JSON data into natural language insights.

Both use LangChain ChatOpenAI for LLM integration (Claude by default, via Anthropic's
OpenAI-compatible endpoint; see resolve_llm_settings).
"""

import os
import json
import re
import asyncio
from datetime import timedelta

from typing import List, Dict, Any, Optional

import httpx
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_openai import ChatOpenAI

from backend.agents.known_locations import find_known_location
from backend.queries.query_utils import DEFAULT_DATA_START, DEFAULT_DATA_END
from backend.queries.date_utils import (
    DateRange,
    clip_to_dataset,
    find_impossible_day,
    iso as _iso,
    month_bounds,
    reference_date,
    resolve_comparison_periods,
    resolve_dates,
    validate_range,
)


# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

class QueryStep(BaseModel):
    """A single data query step in the execution plan."""
    type: str = Field(..., description="Query type: dashboard, timeseries, geo, events, overview, top_events, hot_events, daily_brief, news_context, event_detail, compare_periods")
    params: Dict[str, Any] = Field(default_factory=dict, description="Parameters for the query")


class QueryContext(BaseModel):
    """Structured context extracted from natural language by the local router."""
    user_input: Optional[str] = Field(None, description="Original user query")
    location: Optional[str] = Field(None, description="Canonical location name, e.g. 'Washington DC', 'New York'")
    date_start: Optional[str] = Field(None, description="Start date in YYYY-MM-DD format")
    date_end: Optional[str] = Field(None, description="End date in YYYY-MM-DD format")
    event_type: Optional[str] = Field(None, description="One of: protest, conflict, cooperation")
    query_text: Optional[str] = Field(None, description="Free text search terms")
    intent_category: str = Field("search", description="search | detail | brief | overview | hot | off_topic")
    confidence: str = Field("high", description="high | medium | low")
    date_status: str = Field("none", description="none | valid | invalid | defaulted. Whether the date range was checked, not which parser produced it")
    date_source: str = Field("none", description="none | explicit | deterministic | router")
    date_note: Optional[str] = Field(None, description="User-facing note when dates were defaulted or corrected")
    router: Optional[str] = Field(None, description="Which router produced this context: claude model, qwen2.5:3b, or rules")


class QueryPlan(BaseModel):
    """Structured plan generated by the Planner."""
    intent: str = Field(..., description="Brief description of user intent")
    thinking: Optional[str] = Field(None, description="AI reasoning for tool selection")
    time_range: Optional[Dict[str, str]] = Field(None, description="Resolved date range {start, end} if applicable")
    steps: List[QueryStep] = Field(..., description="Ordered list of queries to execute")
    visualizations: List[str] = Field(..., description="Recommended visualizations: stats_cards, timeline, map, heatmap, event_table, report")
    report_prompt: Optional[str] = Field(None, description="Optional prompt for AI report generation")
    notice: Optional[str] = Field(None, description="User-facing notice about query optimization")
    routing_confidence: Optional[str] = Field(
        None, description="high / medium / low from evidence (see Planner._routing_confidence), not the router's self-report")


class ReportResult(BaseModel):
    """AI-generated report based on query results."""
    summary: str = Field(..., description="Executive summary")
    key_findings: List[str] = Field(default_factory=list, description="Bullet point key findings")


# ---------------------------------------------------------------------------
# LLM Builder (shared between Planner and Report)
# ---------------------------------------------------------------------------

# provider -> (API key env vars in order, default base URL, default model).
# Claude is reached through Anthropic's OpenAI-compatible endpoint, so ChatOpenAI works unchanged.
_LLM_PROVIDERS = {
    "claude": (("ANTHROPIC_API_KEY",), "https://api.anthropic.com/v1/", "claude-sonnet-5-5"),
    "openai": (("OPENAI_API_KEY",), "https://api.openai.com/v1", "gpt-4o"),
}
_LLM_PROVIDER_ALIASES = {"anthropic": "claude"}


def resolve_llm_settings(config: Optional[Dict[str, Any]] = None) -> Dict[str, str]:
    """Provider, key, base URL and model from runtime config, then environment.

    LLM_BASE_URL / LLM_MODEL apply only to the provider named in LLM_PROVIDER: they used to
    apply to every provider, so switching provider sent the new key to the old base URL.
    """
    cfg = config or {}
    env_provider = os.getenv("LLM_PROVIDER", "claude").lower()
    env_provider = _LLM_PROVIDER_ALIASES.get(env_provider, env_provider)
    provider = str(cfg.get("provider") or env_provider).lower()
    provider = _LLM_PROVIDER_ALIASES.get(provider, provider)
    if provider not in _LLM_PROVIDERS:
        raise ValueError(f"Unknown LLM provider: {provider}")

    key_vars, default_url, default_model = _LLM_PROVIDERS[provider]
    from_env = provider == env_provider
    api_key = cfg.get("api_key") or next((os.getenv(v) for v in key_vars if os.getenv(v)), "")
    return {
        "provider": provider,
        "api_key": api_key,
        "base_url": cfg.get("base_url") or (os.getenv("LLM_BASE_URL") if from_env else None) or default_url,
        "model": cfg.get("model") or (os.getenv("LLM_MODEL") if from_env else None) or default_model,
    }


def build_llm(config: Optional[Dict[str, Any]] = None) -> ChatOpenAI:
    """Initialize LLM from environment or runtime config."""
    settings = resolve_llm_settings(config)
    if not settings["api_key"]:
        raise ValueError(f"API key not set for provider: {settings['provider']}")

    # Current Claude models reject `temperature` ("deprecated for this model"); others keep 0.1.
    sampling = {} if settings["provider"] == "claude" else {"temperature": 0.1}
    return ChatOpenAI(
        api_key=settings["api_key"],
        base_url=settings["base_url"],
        model=settings["model"],
        max_tokens=4096,
        **sampling,
    )


# ---------------------------------------------------------------------------
# JSON Extraction Helper
# ---------------------------------------------------------------------------

def _extract_json(text: str) -> Optional[Dict]:
    """Extract JSON from LLM response, handling markdown code blocks and malformed output."""
    text = text.strip()
    
    # Strategy 1: Extract from markdown code block
    match = re.search(r'```(?:json)?\s*\n?(.*?)```', text, re.DOTALL)
    if match:
        candidate = match.group(1).strip()
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass
    
    # Strategy 2: Find outermost JSON object by bracket counting (most reliable)
    start = text.find('{')
    if start != -1:
        depth = 0
        end = start
        for i, ch in enumerate(text[start:], start):
            if ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
                if depth == 0:
                    end = i
                    break
        if depth == 0:
            try:
                return json.loads(text[start:end+1])
            except json.JSONDecodeError:
                pass
    
    # Strategy 3: Simple greedy regex as last resort
    match = re.search(r'(\{.*\})', text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass
    
    return None


def _normalize_plan(raw: Dict) -> QueryPlan:
    """Normalize raw dict to QueryPlan, handling alias variations."""
    steps = []
    for s in raw.get("steps", []):
        step_type = s.get("type") or s.get("query_type") or "events"
        steps.append(QueryStep(type=step_type, params=s.get("params", {})))
    
    return QueryPlan(
        intent=raw.get("intent", "unknown"),
        thinking=raw.get("thinking"),
        time_range=raw.get("time_range"),
        steps=steps,
        visualizations=raw.get("visualizations", ["event_table", "report"]),
        report_prompt=raw.get("report_prompt"),
        notice=raw.get("notice"),
    )


# ---------------------------------------------------------------------------
# Local Ollama Router (qwen2.5:3b)
# ---------------------------------------------------------------------------

# Event IDs anywhere in a sentence: EVT-2024-01-09-123, a fingerprint such as
# US-20240109-FOR-PROTEST-1150442224 (any 2-letter country: CA-..., MX-...), or a bare 9-12 digit ID.
EVENT_ID_IN_TEXT = re.compile(
    r'\b(EVT-\d{4}-\d{2}-\d{2}-\d+|[A-Z]{2}-\d{8}-[A-Z]+-[A-Z]+-\d+)\b|(?<![\d-])(\d{9,12})(?![\d-])',
    re.IGNORECASE,
)

_BRIEF_RE = re.compile(
    r"\b(daily brief|brief|briefing|what happened|what was|summari[sz]e|summary|recap|digest|rundown)\b",
    re.IGNORECASE,
)
_OVERVIEW_RE = re.compile(
    r"\b(overview|situation|what'?s happening|state of"
    r"|how\s+(?:has|have|is|are|was|were)\s+(?:\w+\s+){1,4}(?:been|doing|going))\b",
    re.IGNORECASE,
)
_HOT_RE = re.compile(
    r"\b(hottest|hot|trending|top\s+\d*\s*(?:events?|news|stories|headlines)|"
    r"(?:biggest|largest|major)\s+(?:events?|news|stories|headlines)|"
    r"most\s+(?:popular|reported|mentioned|important|covered))\b",
    re.IGNORECASE,
)


def context_from_router_json(raw: Dict, query: str) -> QueryContext:
    """QueryContext from a router's JSON reply (same schema for the Claude and the local router)."""
    def field(name):
        value = raw.get(name)
        if isinstance(value, str) and value.strip().lower() in ('null', 'none', 'n/a', ''):
            return None
        return value

    location, event_type, query_text = field("location"), field("event_type"), field("query_text")
    date_start, date_end = field("date_start"), field("date_end")
    intent = raw.get("intent_category", "search")
    if intent not in ("search", "detail", "brief", "overview", "hot", "off_topic"):
        intent = "search"

    # If query_text looks like an event fingerprint, force intent=detail and clear all other
    # fields (fingerprint lookup does not need date/location filters).
    check_text = (query_text or "").strip() or query.strip()
    if re.match(r'^(EVT-\d{4}-\d{2}-\d{2}-\d+|US-\d{8}-[A-Z]+-[A-Z]+-\d+|\d{9,12})$', check_text, re.IGNORECASE):
        intent = "detail"
        location = date_start = date_end = event_type = None
        query_text = query_text or check_text

    return QueryContext(
        location=location,
        date_start=date_start,
        date_end=date_end,
        event_type=event_type,
        query_text=query_text,
        intent_category=intent,
        confidence="high",
    )


def detect_intent(text: str) -> str:
    """Keyword intent detection shared by the regex fallback paths."""
    if _BRIEF_RE.search(text):
        return "brief"
    if _OVERVIEW_RE.search(text):
        return "overview"
    if _HOT_RE.search(text):
        return "hot"
    return "search"


class OllamaRouter:
    """Fast local intent router using qwen2.5:3b via Ollama.
    
    Routes queries to one of three categories:
    - rule_base: Simple lookups with explicit filters (time, location, event type, ID)
    - llm_tools: Complex queries requiring reasoning/comparison/synthesis
    - off_topic: Greetings, small talk, unrelated questions
    
    Tries multiple URLs in order (env var → host.docker.internal → localhost)
    to support both Docker and native environments.
    """

    MODEL = "qwen2.5:3b"

    def _get_urls(self) -> list[str]:
        """Return candidate Ollama URLs to try."""
        urls = []
        env_url = os.getenv("OLLAMA_URL")
        if env_url:
            urls.append(env_url)
        # Docker Desktop / host network
        urls.append("http://host.docker.internal:11434/api/generate")
        # Native / Linux Docker with host network
        urls.append("http://localhost:11434/api/generate")
        return urls

    SYSTEM_PROMPT = """You extract structured information from natural language queries for a GDELT event search system.

Extract and return ONLY this JSON format:
{
  "location": "canonical location name or null",
  "date_start": "YYYY-MM-DD or null",
  "date_end": "YYYY-MM-DD or null",
  "event_type": "protest|conflict|cooperation or null",
  "query_text": "free text search terms or null",
  "intent_category": "search|detail|brief|overview|hot|off_topic"
}

Date extraction rules:
- "May 1 2024" → "2024-05-01" to "2024-05-01"
- "Jan 2024" → "2024-01-01" to "2024-01-31"
- "Q1 2024" → "2024-01-01" to "2024-03-31"
- "last week" → the previous Monday-to-Sunday week before the reference date
- "recently" → last 30 days
- "2024" → "2024-01-01" to "2024-12-31"
- null → "2024-01-01" to "2024-12-31"

Location canonicalization:
- "NYC", "NY", "New York City" → "New York"
- "DC", "Washington DC", "Washington, D.C." → "Washington DC"
- "LA" → "Los Angeles"
- "SF" → "San Francisco"
- "TX" → "Texas"

Event type mapping:
- "protest", "demonstration", "rally", "march" → "protest"
- "conflict", "war", "attack", "fight", "battle", "clash" → "conflict"
- "cooperation", "treaty", "agreement", "partnership" → "cooperation"

Intent categories:
- "search": general event search (most common)
- "detail": user provided event ID like EVT-2024-01-15-12345 — WHEN INPUT IS AN EVENT ID: set ONLY intent_category="detail" and query_text="the full EVT-... ID", ALL OTHER FIELDS MUST BE null
- "brief": "daily brief", "what happened on [date]"
- "overview": "situation in [region]", "what's happening in [region]"
- "hot": "hottest event", "top events", "most popular"
- "off_topic": greeting, thanks, small talk

All data is from 2024 only.
No other text. Just the JSON."""

    def __init__(self):
        self._client: Optional[httpx.AsyncClient] = None
        # Compile fallback patterns once
        self._EVENT_ID_PATTERN = re.compile(
            r'^(EVT-\d{4}-\d{2}-\d{2}-\d+)\b|'
            r'^(US-\d{8}-[A-Z]+-[A-Z]+-\d+)\b|'
            r'^\d{9,12}\b',
            re.IGNORECASE,
        )
        # Unanchored: finds the ID inside a sentence ("tell me about event 1150442224").
        # The anchored pattern above only matches when the whole input starts with the ID,
        # which is why natural-language ID lookups never reached the event_detail tool.
        self._EVENT_ID_IN_TEXT = EVENT_ID_IN_TEXT
        self._GREETING_PATTERNS = re.compile(
            r'^(hi|hello|hey|greetings|good morning|good afternoon|good evening|thanks|thank you|bye|goodbye|ok|okay)\b',
            re.IGNORECASE,
        )
        self._MONTH_YEAR_PATTERN = re.compile(
            r'\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+(\d{4})\b',
            re.IGNORECASE,
        )
        self._FULL_DATE_PATTERN = re.compile(
            r'\b(\d{4})[-/](\d{1,2})[-/](\d{1,2})\b|'
            r'\b(\d{1,2})[-/](\d{1,2})[-/](\d{4})\b|'
            r'\b(\d{4})(\d{2})(\d{2})\b',
        )
        self._LOCATION_PATTERN = re.compile(
            r'\b(?:in|at|near|around|on)\s+([A-Z][A-Za-z\s,]+?)(?=\s+(?:in|at|near|around|on|during|for|from|to|of|with|this|last|'
            r'\d{4}|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*|\?|$)|$)',
            re.IGNORECASE,
        )
        self._MONTH_MAP = {
            'jan': '01', 'feb': '02', 'mar': '03', 'apr': '04', 'may': '05', 'jun': '06',
            'jul': '07', 'aug': '08', 'sep': '09', 'oct': '10', 'nov': '11', 'dec': '12',
        }

    @property
    def client(self) -> httpx.AsyncClient:
        if self._client is None:
            self._client = httpx.AsyncClient(timeout=httpx.Timeout(10.0, connect=2.0))
        return self._client

    async def extract_context(self, query: str) -> QueryContext:
        """Extract structured context from natural language query.
        Tries each Ollama URL in order. Falls back to regex-based extraction on total failure.
        """
        prompt = (
            f"{self.SYSTEM_PROMPT}\n\n"
            f"Reference date for relative phrases (treat this as 'today'): {_iso(reference_date())}\n\n"
            f"Query: \"{query}\"\n\nJSON:"
        )
        last_error = None
        
        for url in self._get_urls():
            try:
                resp = await self.client.post(
                    url,
                    json={
                        "model": self.MODEL,
                        "prompt": prompt,
                        "stream": False,
                        "options": {"temperature": 0.0, "num_predict": 120},
                    },
                )
                resp.raise_for_status()
                data = resp.json()
                text = data.get("response", "").strip()
                
                raw = _extract_json(text)
                if raw is None:
                    continue
                ctx = context_from_router_json(raw, query)
                ctx.router = self.MODEL
                return ctx

            except Exception as e:
                last_error = e
                continue
        
        print(f"[OllamaRouter] All URLs failed (last: {last_error}), falling back to regex extraction", flush=True)
        ctx = self._fallback_extract_context(query)
        ctx.router = "rules"
        return ctx

    def _fallback_extract_context(self, query: str) -> QueryContext:
        """Regex-based fallback extraction when Ollama router fails."""
        q = query.lower().strip()
        
        # Greeting check
        if len(q) < 3 or self._GREETING_PATTERNS.match(q):
            return QueryContext(intent_category="off_topic", confidence="low")
        
        # Event ID check
        evt_match = self._EVENT_ID_IN_TEXT.search(query.strip())
        if evt_match:
            return QueryContext(intent_category="detail", confidence="low", query_text=evt_match.group(0))
        
        # Location
        location = None
        loc_match = self._LOCATION_PATTERN.search(query)
        if loc_match:
            location = loc_match.group(1).strip()
        else:
            # Generated from the data (db_scripts/build_known_locations.py): US, Canada, Mexico.
            location = find_known_location(query)
        if location:
            location = re.sub(r'\s+(in|at|near|around|on|during|for|from|to|of|with)$', '', location, flags=re.IGNORECASE).strip()
            if location.lower() in ('dc', 'washington dc', 'washington, dc'):
                location = 'Washington DC'
        
        # Date range
        start_date, end_date = None, None
        nat_match = self._NATURAL_DATE_PATTERN.search(query) if hasattr(self, '_NATURAL_DATE_PATTERN') else None
        if nat_match:
            if nat_match.group(1):
                month_abbr = nat_match.group(1).lower()[:3]
                d = nat_match.group(2).zfill(2)
                y = nat_match.group(3)
                start_date = f"{y}-{self._MONTH_MAP.get(month_abbr, '01')}-{d}"
                end_date = start_date
            elif nat_match.group(4):
                d = nat_match.group(4).zfill(2)
                month_abbr = nat_match.group(5).lower()[:3]
                y = nat_match.group(6)
                start_date = f"{y}-{self._MONTH_MAP.get(month_abbr, '01')}-{d}"
                end_date = start_date
        
        if not start_date:
            full_match = self._FULL_DATE_PATTERN.search(query)
            if full_match:
                if full_match.group(1):
                    start_date = f"{full_match.group(1)}-{full_match.group(2).zfill(2)}-{full_match.group(3).zfill(2)}"
                    end_date = start_date
                elif full_match.group(4):
                    start_date = f"{full_match.group(6)}-{full_match.group(4).zfill(2)}-{full_match.group(5).zfill(2)}"
                    end_date = start_date
                elif full_match.group(7):
                    start_date = f"{full_match.group(7)}-{full_match.group(8)}-{full_match.group(9)}"
                    end_date = start_date
        
        if not start_date:
            my_match = self._MONTH_YEAR_PATTERN.search(query)
            if my_match:
                month_abbr = my_match.group(1).lower()[:3]
                y = my_match.group(2)
                m = self._MONTH_MAP.get(month_abbr, '01')
                first, last = month_bounds(int(y), int(m))
                start_date, end_date = _iso(first), _iso(last)
        
        # Event type
        event_type = None
        if 'protest' in q or 'demonstration' in q or 'rally' in q or 'march' in q:
            event_type = 'protest'
        elif 'conflict' in q or 'war' in q or 'attack' in q or 'fight' in q or 'battle' in q or 'clash' in q:
            event_type = 'conflict'
        elif 'cooperation' in q or 'treaty' in q or 'agreement' in q or 'partnership' in q:
            event_type = 'cooperation'
        
        # The fallback used to return intent="search" for everything, so a "daily brief"
        # or "regional overview" question was misrouted to a generic event search.
        intent = detect_intent(q)

        return QueryContext(
            intent_category=intent,
            confidence="low",
            location=location,
            date_start=start_date,
            date_end=end_date,
            event_type=event_type,
            query_text=query.strip(),
        )

    async def extract_context_fast(self, query: str) -> QueryContext:
        """Fast-path context extraction using regex only — no Ollama call.
        
        Used for queries with obvious structured filters (date, location, event_type)
        where we don't need LLM reasoning. Returns in < 5ms vs 2s for Ollama.
        """
        import time
        t0 = time.time()
        
        q_lower = query.lower()
        
        # Date extraction
        date_start, date_end = None, None
        
        # Full date: "Jan 25 2024", "January 25, 2024", "2024-01-25"
        m = re.search(r'(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\.?\s+(\d{1,2})(?:st|nd|rd|th)?[,\s]+(2024)', q_lower)
        if m:
            month_map = {'jan':1,'feb':2,'mar':3,'apr':4,'may':5,'jun':6,
                         'jul':7,'aug':8,'sep':9,'oct':10,'nov':11,'dec':12}
            month_abbr = q_lower[m.start():m.start()+3]
            month = month_map.get(month_abbr, 1)
            day = int(m.group(1))
            date_start = date_end = f"2024-{month:02d}-{day:02d}"
        else:
            m = re.search(r'(\d{4})-(\d{2})-(\d{2})', query)
            if m:
                date_start = date_end = m.group(0)
        
        # Month only: "feb 2024", "in february"
        if not date_start:
            m = re.search(r'(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*', q_lower)
            if m:
                month_map = {'jan':1,'feb':2,'mar':3,'apr':4,'may':5,'jun':6,
                             'jul':7,'aug':8,'sep':9,'oct':10,'nov':11,'dec':12}
                month_abbr = q_lower[m.start():m.start()+3]
                month = month_map.get(month_abbr, 1)
                first, last = month_bounds(2024, month)
                date_start, date_end = _iso(first), _iso(last)
        
        # Location extraction
        location = None
        loc_patterns = [
            (r'(?:near|in|around)\s+(?:the\s+)?white\s+house', 'Washington DC'),
            (r'(?:near|in|around)\s+(?:washington\s+dc?|washington,\s*d\.?c\.?)', 'Washington DC'),
            (r'(?:near|in|around)\s+(?:new\s+york\s+city?|nyc|new\s+york)', 'New York'),
            (r'(?:near|in|around)\s+(?:los\s+angeles|la)', 'Los Angeles'),
            (r'(?:near|in|around)\s+(?:san\s+francisco|sf)', 'San Francisco'),
            (r'(?:near|in|around)\s+texas', 'Texas'),
            (r'(?:near|in|around)\s+california', 'California'),
            (r'(?:near|in|around)\s+florida', 'Florida'),
        ]
        for pattern, canonical in loc_patterns:
            if re.search(pattern, q_lower):
                location = canonical
                break
        
        # Event type extraction
        event_type = None
        if 'protest' in q_lower or 'demonstration' in q_lower or 'rally' in q_lower:
            event_type = 'protest'
        elif 'conflict' in q_lower or 'war' in q_lower or 'attack' in q_lower:
            event_type = 'conflict'
        elif 'cooperation' in q_lower or 'treaty' in q_lower or 'agreement' in q_lower:
            event_type = 'cooperation'
        
        # Intent: brief if "what happened", otherwise search
        intent = 'search'
        if re.search(r'what\s+happened|daily\s+brief|what\s+was', q_lower):
            intent = 'brief'
        
        # Query text: strip out obvious filter words to keep only meaningful search terms
        query_text = query
        
        elapsed_ms = round((time.time() - t0) * 1000, 3)
        print(f"[OllamaRouter] Fast-path regex extraction: {elapsed_ms}ms | loc={location}, date={date_start}, type={event_type}, intent={intent}", flush=True)
        
        return QueryContext(
            location=location,
            date_start=date_start,
            date_end=date_end,
            event_type=event_type,
            query_text=query_text,
            intent_category=intent,
            confidence="high" if validate_range(date_start, date_end).ok or not date_start else "low",
        )

    async def close(self):
        if self._client:
            await self._client.aclose()
            self._client = None


class ClaudeRouter:
    """Context extraction with Claude (ROUTER_MODEL, default claude-sonnet-5-5), same JSON schema
    and prompt as the local router.

    The 3B router mislabelled questions the rules had not been written for (each new held-out set
    needed new rule fixes), so the default router is now Claude, with the local model as the
    fallback when there is no key or the call fails (and the regex rules behind that). The
    planner's deterministic checks (dates, labels against the user's words) apply to either router.
    """

    def __init__(self, fallback: Optional["OllamaRouter"] = None, config: Optional[Dict[str, Any]] = None):
        self.fallback = fallback or OllamaRouter()
        self._config = config
        self._llm: Optional[ChatOpenAI] = None
        self.model = os.getenv("ROUTER_MODEL", "claude-sonnet-5-5")

    def _client(self) -> ChatOpenAI:
        if self._llm is None:
            cfg = dict(self._config or {}, provider="claude", model=self.model)
            settings = resolve_llm_settings(cfg)
            if not settings["api_key"]:
                raise ValueError("ANTHROPIC_API_KEY not set")
            # max_tokens covers the model's reasoning as well as the JSON: at 300, Sonnet 5.5 spent
            # the whole budget reasoning about impossible dates and "this week" and returned no text
            # (finish_reason=length) on 12 of 118 eval questions.
            self._llm = ChatOpenAI(api_key=settings["api_key"], base_url=settings["base_url"],
                                   model=settings["model"], max_tokens=2048, timeout=30, max_retries=1)
        return self._llm

    async def extract_context(self, query: str) -> QueryContext:
        messages = [
            SystemMessage(content=OllamaRouter.SYSTEM_PROMPT),
            HumanMessage(content=(
                f"Reference date for relative phrases (treat this as 'today'): {_iso(reference_date())}\n\n"
                f"Query: \"{query}\"\n\nJSON:")),
        ]
        try:
            response = await self._client().ainvoke(messages)
            raw = _extract_json(response.content if hasattr(response, "content") else str(response))
            if raw is None:
                raise ValueError("no JSON in the router reply")
            ctx = context_from_router_json(raw, query)
            ctx.router = self.model
            return ctx
        except Exception as e:
            print(f"[ClaudeRouter] {type(e).__name__}: {e}; using the local router", flush=True)
            return await self.fallback.extract_context(query)

    async def close(self):
        await self.fallback.close()


def build_router():
    """ROUTER_PROVIDER=claude (default) or ollama (local qwen2.5:3b only)."""
    if os.getenv("ROUTER_PROVIDER", "claude").lower() == "ollama":
        return OllamaRouter()
    return ClaudeRouter()


# ---------------------------------------------------------------------------
# Planner
# ---------------------------------------------------------------------------

PLANNER_SYSTEM_PROMPT = """You are GDELT Event Search AI. Your job is to find specific events and incidents. Output ONLY raw JSON.

JSON schema:
{
  "thinking": "1-sentence reasoning",
  "intent": "short description",
  "time_range": {"start": "YYYY-MM-DD", "end": "YYYY-MM-DD"} or null,
  "steps": [{"type": "QUERY_TYPE", "params": {...}}],
  "visualizations": ["event_table", "report"],
  "report_prompt": "prompt for AI analysis"
}

Available tools (event search only):
- events: {query, start_date, end_date, location_hint, event_type, actor, limit} — broad event search
- event_detail: {fingerprint} — specific event by EVT-ID
- similar_events: {seed_event_id} — find events similar to a given event (pair with event_detail)
- hot_events: {query_date, top_n} — hottest single-day events
- top_events: {start_date, end_date, region_filter, event_type, top_n} — top events across a time range
- daily_brief: {query_date} — daily summary of key events
- regional_overview: {start_date, end_date, region} — situation summary for a specific region
- compare_periods: {periods: [{label, start, end}, {label, start, end}], location_hint, event_type} — COMPLETE event counts for two periods and a computed change. Use it for any "did X increase/decrease", "compared with", "more/less than" question. Never infer totals or trends from the events tool: it returns a top-N sample.
- news_context: {query, n_results} — semantic search over news article text (use alongside events to add context)

Date rules:
- Relative dates are resolved against the reference date given in the request, never the current date.
- "last month" = previous calendar month
- "this week" = Mon-Sun week containing the reference date
- "recently" = the 30 days ending on the reference date
- no time given = the full dataset period
- "Feb 2024" = 2024-02-01 to 2024-02-29
- "Q3 2024" = 2024-07-01 to 2024-09-30
- All data is 2024 only.

Off-topic → {"intent": "off_topic", "steps": [], "visualizations": []}

Rules:
- thinking: 1 sentence max.
- Max 2 steps.
- You do NOT do data analysis, trends, dashboards, or maps — those are handled by the Dashboard tab.
- Always include "report" in visualizations."""


class Planner:
    """Hybrid planner: local Ollama router → rule-based fast path OR remote LLM tool execution."""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self._llm_config = config
        self._llm: Optional[ChatOpenAI] = None
        self.router = build_router()

    @property
    def llm(self) -> ChatOpenAI:
        if self._llm is None:
            self._llm = build_llm(self._llm_config)
        return self._llm

    # Quick off-topic / greeting detection without LLM
    # Trailing punctuation is allowed ("thanks!", "hi."): without it those inputs
    # missed the fast path and cost an Ollama call.
    _GREETING_PATTERNS = re.compile(
        r'^(?:(?:hi+|hello|hey|thanks?(?:\s+you)?|thank you|ok+(?:ay)?|bye|goodbye|see you|'
        r'good\s+(?:morning|afternoon|evening))[\s!.,?]*|[\s?!.]+)$',
        re.IGNORECASE
    )

    # Detect if user explicitly mentions a time range
    _TIME_MENTIONED = re.compile(
        r'\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\b|'
        r'\b\d{4}\b|'
        r'\b(this|last|past)\s+(week|month|year|day)\b|'
        r'\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b|'
        r'\byesterday\b|\btoday\b',
        re.IGNORECASE,
    )

    # Extract location from "... in/at/near/around/on <place>"
    # Terminates at next preposition, time word, or end of string
    _LOCATION_PATTERN = re.compile(
        r'\b(?:in|at|near|around|on)\s+([A-Z][A-Za-z\s,]+?)(?=\s+(?:in|at|near|around|on|during|for|from|to|of|with|this|last|'
        r'\d{4}|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*|\?|$)|$)',
        re.IGNORECASE,
    )


    # Hot / top events keywords (used by fallback extraction only)
    _HOT_KEYWORDS = re.compile(
        r'\b(hottest|hot|top(?:\s+\d+)?(?:\s+(?:events?|news?|stories?))?|most\s+(?:popular|reported|mentioned|important)|trending)\b',
        re.IGNORECASE,
    )

    # Detect specific event ID patterns (EVT-..., US-YYYYMMDD-LOC-TYPE-NUM, or raw numeric ID)
    _EVENT_ID_PATTERN = re.compile(
        r'^(EVT-\d{4}-\d{2}-\d{2}-\d+)\b|'
        r'^(US-\d{8}-[A-Z]+-[A-Z]+-\d+)\b|'
        r'^\d{9,12}\b',
        re.IGNORECASE,
    )

    # Parse month+year like "march 2024" or "feb 2024" (fallback only)
    _MONTH_YEAR_PATTERN = re.compile(
        r'\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+(\d{4})\b',
        re.IGNORECASE,
    )
    _MONTH_MAP = {
        'jan': '01', 'feb': '02', 'mar': '03', 'apr': '04', 'may': '05', 'jun': '06',
        'jul': '07', 'aug': '08', 'sep': '09', 'oct': '10', 'nov': '11', 'dec': '12',
    }

    # Parse full numeric dates: 2024-10-15, 10/15/2024, 20241015 (fallback only)
    _FULL_DATE_PATTERN = re.compile(
        r'\b(\d{4})[-/](\d{1,2})[-/](\d{1,2})\b|'
        r'\b(\d{1,2})[-/](\d{1,2})[-/](\d{4})\b|'
        r'\b(\d{4})(\d{2})(\d{2})\b',
    )

    # Parse natural language dates: "May 1 2024", "1 May 2024" (fallback only)
    _NATURAL_DATE_PATTERN = re.compile(
        r'\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+(\d{1,2})(?:st|nd|rd|th)?,?\s+(\d{4})\b|'
        r'\b(\d{1,2})(?:st|nd|rd|th)?\s+(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+(\d{4})\b',
        re.IGNORECASE,
    )

    # Location extraction (fallback only)
    _LOCATION_PATTERN = re.compile(
        r'\b(?:in|at|near|around|on)\s+([A-Z][A-Za-z\s,]+?)(?=\s+(?:in|at|near|around|on|during|for|from|to|of|with|this|last|'
        r'\d{4}|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*|\?|$)|$)',
        re.IGNORECASE,
    )


    # -----------------------------------------------------------------------
    # Fallback Entity Extraction (when Ollama is unavailable)
    # -----------------------------------------------------------------------

    # (Moved to OllamaRouter class above)

    # -----------------------------------------------------------------------
    # Rule-Based Planner (uses structured context from router)
    # -----------------------------------------------------------------------

    def _rule_based_plan(self, ctx: QueryContext) -> Optional[QueryPlan]:
        """Fast rule-based planner using structured context from Ollama router."""
        # Off-topic
        if ctx.intent_category == "off_topic":
            return QueryPlan(
                intent="off_topic",
                thinking="User input is a greeting or too short — no tools needed.",
                steps=[],
                visualizations=[],
                report_prompt=None,
            )

        # Event detail lookup
        if ctx.intent_category == "detail":
            # Try user_input first, then query_text (Ollama may put fingerprint there)
            search_text = (ctx.user_input or "") + " " + (ctx.query_text or "")
            evt_match = EVENT_ID_IN_TEXT.search(search_text)
            if evt_match:
                fingerprint = evt_match.group(1) or evt_match.group(2)
                # Seed for similar_events: the GlobalEventID. A bare ID is one; EVT-... and the
                # fingerprints (US-/CA-/MX-..., see precompute_sql) end with it. The old code
                # handled only US- and EVT-, so a CA- fingerprint hit int() and returned HTTP 400.
                last = fingerprint.split('-')[-1]
                seed_id = int(last) if last.isdigit() and len(last) >= 9 else None
                steps = [QueryStep(type="event_detail", params={"fingerprint": fingerprint})]
                if seed_id:
                    steps.append(QueryStep(type="similar_events", params={"seed_event_id": seed_id, "limit": 10}))
                return QueryPlan(
                    intent="event_detail_lookup",
                    thinking="User provided a specific event ID — retrieving event details + similar events.",
                    steps=steps,
                    visualizations=["event_table", "report"],
                    report_prompt=f"Summarize this specific GDELT event ({fingerprint}) and highlight related events.",
                )

        # Daily brief
        if ctx.intent_category == "brief":
            # Default to the day before the dataset anchor, never the wall clock:
            # the data is a static 2024 extract, so "today" would match zero rows.
            query_date = ctx.date_start or _iso(reference_date() - timedelta(days=1))
            end_date = ctx.date_end or query_date
            if ctx.location and ctx.date_status == "invalid":
                # The user named a day we could not use; an arbitrary other day would mislead.
                query_date, end_date = DEFAULT_DATA_START, DEFAULT_DATA_END

            # If location is provided, search events in that location instead of global daily stats
            if ctx.location:
                params: Dict[str, Any] = {
                    "limit": 20,
                    "start_date": query_date,
                    "end_date": end_date,
                    "location_hint": ctx.location,
                }
                if ctx.event_type:
                    params["event_type"] = ctx.event_type
                span = f"on {query_date}" if query_date == end_date else f"from {query_date} to {end_date}"
                return QueryPlan(
                    intent=f"events_{ctx.location}_{query_date}",
                    thinking=f"User requested events in {ctx.location} {span}. Searching for location-matched events.",
                    steps=[QueryStep(type="events", params=params)],
                    visualizations=["event_table", "report"],
                    report_prompt=f"Summarize what happened in {ctx.location} {span}.",
                )

            # No location — return global daily summary
            return QueryPlan(
                intent="daily_brief",
                thinking=f"User requested daily brief for {query_date}.",
                steps=[QueryStep(type="daily_brief", params={"query_date": query_date})],
                visualizations=["stats_cards", "report"],
                report_prompt=f"Summarize the key events on {query_date}.",
            )

        # Hot / Top events
        if ctx.intent_category == "hot":
            is_single_day = ctx.date_start is not None and ctx.date_end is not None and ctx.date_start == ctx.date_end
            if is_single_day:
                params = {"query_date": ctx.date_start, "top_n": 10}
                if ctx.location:
                    params["region_filter"] = ctx.location
                return QueryPlan(
                    intent=f"hot_events_{ctx.location or 'global'}",
                    thinking=f"User requested hot events for {ctx.date_start}." + (f" Filtering by region: {ctx.location}." if ctx.location else ""),
                    steps=[QueryStep(type="hot_events", params=params)],
                    visualizations=["event_table", "report"],
                    report_prompt=f"Summarize the hottest events on {ctx.date_start}" + (f" in {ctx.location}" if ctx.location else "") + ".",
                )
            else:
                params = {
                    "start_date": ctx.date_start or DEFAULT_DATA_START,
                    "end_date": ctx.date_end or DEFAULT_DATA_END,
                    "top_n": 10,
                }
                if ctx.location:
                    params["region_filter"] = ctx.location
                if ctx.event_type:
                    params["event_type"] = ctx.event_type
                return QueryPlan(
                    intent=f"top_events_{ctx.event_type or 'all'}_{ctx.location or 'global'}",
                    thinking=f"User requested top events" + (f" ({ctx.event_type})" if ctx.event_type else "") + (f" in {ctx.location}" if ctx.location else "") + f" from {params['start_date']} to {params['end_date']}.",
                    steps=[QueryStep(type="top_events", params=params)],
                    visualizations=["event_table", "report"],
                    report_prompt=f"Summarize the top {ctx.event_type or ''} events" + (f" in {ctx.location}" if ctx.location else "") + f" from {params['start_date']} to {params['end_date']}.",
                )

        # Regional overview
        if ctx.intent_category == "overview" and ctx.location:
            params = {"region": ctx.location}
            if ctx.date_start and ctx.date_end:
                params["start_date"] = ctx.date_start
                params["end_date"] = ctx.date_end
            else:
                params["time_range"] = "week"
            return QueryPlan(
                intent=f"regional_overview_{ctx.location}",
                thinking=f"User requested regional overview for {ctx.location}." + (f" Time range: {ctx.date_start} to {ctx.date_end}." if ctx.date_start else " Default: last week."),
                steps=[QueryStep(type="regional_overview", params=params)],
                visualizations=["stats_cards", "event_table", "report"],
                report_prompt=f"Provide a situation overview for {ctx.location}" + (f" from {ctx.date_start} to {ctx.date_end}" if ctx.date_start else " over the last week") + ".",
            )

        # Underspecified: no location, type, dates or usable text. The old code fell
        # through to a generic event search here, which made the remote-LLM fallback in
        # plan() unreachable. Returning None lets plan() hand these to it.
        if self._is_underspecified(ctx):
            return None

        # Default: events search
        params: Dict[str, Any] = {
            "limit": 50,
            "start_date": ctx.date_start or DEFAULT_DATA_START,
            "end_date": ctx.date_end or DEFAULT_DATA_END,
        }
        if ctx.location:
            params["location_hint"] = ctx.location
        if ctx.event_type:
            params["event_type"] = ctx.event_type
        if ctx.query_text:
            params["query"] = ctx.query_text
        
        intent_name = f"events_{ctx.event_type or 'all'}_{ctx.location or 'global'}"
        return QueryPlan(
            intent=intent_name,
            thinking="Event search based on extracted location, date, and event type.",
            steps=[QueryStep(type="events", params=params)],
            visualizations=["event_table", "report"],
            report_prompt=f"Summarize {ctx.event_type or 'events'} {f'in {ctx.location}' if ctx.location else ''} from {params['start_date']} to {params['end_date']}.",
        )

    @staticmethod
    def _is_underspecified(ctx: QueryContext) -> bool:
        """True when a "search" has nothing to filter on.

        Free text alone is a legitimate keyword search ("Uvalde school shooting
        response"), so on the regex-fallback path (low confidence, where query_text is
        just the whole sentence) only very short inputs count as ambiguous.
        """
        if ctx.intent_category != "search" or ctx.location or ctx.event_type or ctx.date_start:
            return False
        if not ctx.query_text:
            return True
        return ctx.confidence == "low" and len(ctx.query_text.split()) < 4

    # -----------------------------------------------------------------------
    # Date resolution (single source of truth: backend.queries.date_utils)
    # -----------------------------------------------------------------------

    def _resolve_dates(self, ctx: QueryContext, query: str) -> None:
        """Make ``ctx`` dates deterministic and validated.

        Order of trust:
          1. A date expression in the user's own words, parsed deterministically
             against the dataset anchor. This wins over the router: the 3B model
             was never given a reference date and returned 131-day windows for
             "last week".
          2. Router dates, kept only if they pass ``validate_range``.
          3. Otherwise no dates, with a note, so callers default explicitly
             instead of silently trusting a bad range labelled high-confidence.
        """
        ctx.date_note = None
        impossible = find_impossible_day(query)
        if impossible:
            # The router "repairs" 2024-02-30 to 2024-02-29 without saying so.
            ctx.date_status, ctx.date_source = "invalid", "deterministic"
            # plan() appends the window actually queried, so the note cannot disagree with the plan.
            ctx.date_note = f"'{impossible}' is not a real calendar date, so it was not used."
            ctx.date_start = ctx.date_end = None
            ctx.confidence = "low"
            return

        resolved = resolve_dates(query)
        clipped_note = ""
        if resolved is not None and resolved.kind != "month":
            # "this week" on Tuesday 2024-12-31 is Dec 30 to Jan 5; only Dec 30-31 has data.
            inside = clip_to_dataset(resolved)
            if inside is not None and inside is not resolved:
                clipped_note = f", limited to the data available ({inside.start_iso} to {inside.end_iso})"
                resolved = inside
        if resolved is not None:
            check = validate_range(resolved.start_iso, resolved.end_iso, resolved.kind if resolved.kind == "month" else None)
            if check.ok:
                if clipped_note or (ctx.date_start, ctx.date_end) != (resolved.start_iso, resolved.end_iso):
                    ctx.date_note = (
                        f"Interpreted '{resolved.label}' as {resolved.start_iso} to {resolved.end_iso}{clipped_note} "
                        f"(relative dates are anchored to {_iso(reference_date())}, the end of the dataset)."
                    )
                ctx.date_start, ctx.date_end = resolved.start_iso, resolved.end_iso
                ctx.date_status, ctx.date_source = "valid", "deterministic"
                return
            ctx.date_status = "invalid"
            ctx.date_note = f"Could not use '{resolved.label}': " + "; ".join(check.problems) + "."
            ctx.date_start = ctx.date_end = None
            ctx.confidence = "low"
            return

        if ctx.date_start or ctx.date_end:
            check = validate_range(ctx.date_start, ctx.date_end or ctx.date_start)
            if check.ok:
                ctx.date_end = ctx.date_end or ctx.date_start
                ctx.date_status, ctx.date_source = "valid", "router"
                return
            ctx.date_status = "invalid"
            ctx.date_note = (
                "The date range could not be interpreted ("
                + "; ".join(check.problems)
                + "), so it was not used."
            )
            ctx.date_start = ctx.date_end = None
            ctx.confidence = "low"
            return

        ctx.date_status, ctx.date_source = "none", "none"

    @staticmethod
    def _routing_confidence(ctx: QueryContext, router_label: str, router_dates: tuple) -> tuple[str, List[str]]:
        """Confidence from evidence, not the 3B router's self-report (which said "high" for
        nearly everything, including the wrong labels the held-out set exposed).

        low: the router's label was overridden by the user's words, or its extraction failed (regex
        fallback). medium: the label stood but the dates were re-derived from the text. high: label
        and dates agreed with the deterministic checks.

        An impossible date in the question ("2024-06-31") used to make it low. It is the user's
        date, not a routing error, and the plan already carries a notice: all 5 such dev questions
        were planned correctly by both routers (2026-10-09), so it no longer lowers the level.
        """
        reasons = []
        if ctx.intent_category != router_label:
            reasons.append(f"router label '{router_label}' overridden to '{ctx.intent_category}'")
        if ctx.confidence == "low" and not reasons:
            reasons.append("router extraction fell back to rules")
        if reasons:
            return "low", reasons
        if ctx.date_source == "deterministic" and router_dates != (ctx.date_start, ctx.date_end):
            return "medium", [f"router dates {router_dates[0]}..{router_dates[1]} replaced from the text"]
        return "high", []

    @staticmethod
    def _queried_window(plan: QueryPlan) -> Optional[str]:
        """The date window the plan will actually query, read from its first step."""
        for step in plan.steps:
            p = step.params
            if p.get("start_date") and p.get("end_date"):
                return f"{p['start_date']} to {p['end_date']}"
            if p.get("query_date"):
                return p["query_date"]
        return None

    def _recover_location(self, ctx: QueryContext) -> None:
        """Fill ``ctx.location`` from the user's words when the router left it empty.

        The router sometimes puts the place into query_text instead
        ("how has California been this month" -> location=None).
        """
        if ctx.location:
            return
        # Short names ("US") only match as written, so "tell us" is not the United States.
        loc = find_known_location(ctx.user_input or "")
        if loc:
            ctx.location = loc

    def _comparison_plan(self, ctx: QueryContext, periods: tuple[DateRange, DateRange]) -> QueryPlan:
        """Plan for "did X increase": two complete periods, counted, then compared."""
        earlier, later = periods
        text = ctx.user_input or ""
        self._recover_location(ctx)
        if not ctx.event_type:
            lowered = text.lower()
            if any(w in lowered for w in ("protest", "demonstration", "rally")):
                ctx.event_type = "protest"
            elif any(w in lowered for w in ("conflict", "attack", "clash", "battle")):
                ctx.event_type = "conflict"
            elif any(w in lowered for w in ("cooperation", "treaty", "agreement", "partnership")):
                ctx.event_type = "cooperation"
        params: Dict[str, Any] = {
            "periods": [
                {"label": earlier.label, "start": earlier.start_iso, "end": earlier.end_iso},
                {"label": later.label, "start": later.start_iso, "end": later.end_iso},
            ],
        }
        if ctx.location:
            params["location_hint"] = ctx.location
        if ctx.event_type:
            params["event_type"] = ctx.event_type
        where = f" in {ctx.location}" if ctx.location else ""
        what = ctx.event_type or "event"
        notes = [
            f"Comparing {what} counts{where}: {earlier.label} ({earlier.start_iso} to {earlier.end_iso}) "
            f"vs {later.label} ({later.start_iso} to {later.end_iso}). "
            f"Relative dates are anchored to {_iso(reference_date())}, the end of the dataset."
        ]
        if not ctx.location:
            notes.append("No location was recognised, so counts cover the whole dataset region.")
        return QueryPlan(
            intent=f"compare_periods_{ctx.event_type or 'all'}_{ctx.location or 'global'}",
            thinking=(
                f"The question compares two periods, so I count every matching event in {earlier.label} "
                f"and {later.label} and compute the change deterministically instead of summarising a sample."
            ),
            time_range={"start": earlier.start_iso, "end": later.end_iso},
            steps=[QueryStep(type="compare_periods", params=params)],
            visualizations=["comparison", "report"],
            report_prompt=(
                f"Explain this period comparison for {what} events{where}. "
                "Quote the verdict and the counts exactly as given and do not recompute them."
            ),
            notice=" ".join(notes),
        )

    # -----------------------------------------------------------------------
    # LLM Tool Planner
    # -----------------------------------------------------------------------

    async def _llm_plan(self, query: str, ctx: QueryContext) -> QueryPlan:
        """Use remote LLM for complex queries. Passes simplified context extracted by Ollama."""
        # Build simplified user intent from structured context
        parts = []
        if ctx.location:
            parts.append(f"Location: {ctx.location}")
        if ctx.date_start:
            if ctx.date_start == ctx.date_end:
                parts.append(f"Date: {ctx.date_start}")
            else:
                parts.append(f"Date range: {ctx.date_start} to {ctx.date_end}")
        if ctx.event_type:
            parts.append(f"Event type: {ctx.event_type}")
        if ctx.query_text:
            parts.append(f"Search terms: {ctx.query_text}")
        
        simplified = "; ".join(parts) if parts else query
        
        # Also attach original query as reference
        user_msg = (
            f"Reference date (treat as today): {_iso(reference_date())}\n"
            f"Simplified user intent: {simplified}\n\nOriginal request: \"{query}\""
        )
        
        # Add any extra context from Ollama
        context_parts = []
        if ctx.intent_category != "search":
            context_parts.append(f"Intent category: {ctx.intent_category}")
        context_str = "\n".join(context_parts) if context_parts else ""
        if context_str:
            user_msg += f"\n\nExtracted context:\n{context_str}"
        user_msg += "\n\nRespond with ONLY raw JSON:"

        messages = [
            SystemMessage(content=PLANNER_SYSTEM_PROMPT),
            HumanMessage(content=user_msg),
        ]

        try:
            response = await asyncio.wait_for(self.llm.ainvoke(messages), timeout=120.0)
            content = response.content if hasattr(response, "content") else str(response)
            print(f"[Planner] raw response length: {len(content)}", flush=True)

            raw = _extract_json(content)
            if raw is None:
                # Print full response for debugging (truncated if very long)
                debug_content = content if len(content) < 800 else content[:400] + "\n... [truncated]\n" + content[-200:]
                print(f"[Planner] JSON extraction failed. Raw response:\n{debug_content}", flush=True)
                raise ValueError("Could not extract valid JSON from LLM response")

            plan = _normalize_plan(raw)
            print(f"[Planner] generated plan: {plan.intent} with {len(plan.steps)} steps", flush=True)
            return plan

        except asyncio.TimeoutError:
            print(f"[Planner] LLM timeout after 120s, using fallback plan", flush=True)
            return self._fallback_plan(query)
        except Exception as e:
            print(f"[Planner] failed: {e}, using fallback plan", flush=True)
            return self._fallback_plan(query)

    def _fallback_plan(self, query: str) -> QueryPlan:
        """Fallback when LLM or router fails."""
        return QueryPlan(
            intent="fallback_search",
            thinking="Planner error. Falling back to top events search.",
            steps=[QueryStep(type="top_events", params={"top_n": 20, "start_date": DEFAULT_DATA_START, "end_date": DEFAULT_DATA_END})],
            visualizations=["event_table", "report"],
            report_prompt=f"Top events for: {query}",
            notice="Planner error. Showing top-ranked events across the full dataset (fast mode). Add a month or date for more precise results.",
        )

    # -----------------------------------------------------------------------
    # Main Entry Point
    # -----------------------------------------------------------------------

    async def plan(self, user_query: str) -> tuple[QueryPlan, List[Dict[str, Any]]]:
        """Generate a query plan from user input.
        
        Simple flow:
        1. Ollama extracts structured context (location, date, event_type, intent).
        2. Rule-based planner directly maps context to tool calls.
        3. Only truly ambiguous queries fall back to remote LLM.
        Returns (QueryPlan, phases).
        """
        import time
        phases: List[Dict[str, Any]] = []
        stripped = user_query.strip()

        # Fast path: greetings (avoid even calling router)
        if self._GREETING_PATTERNS.match(stripped) or len(stripped) < 3:
            print(f"[Planner] Fast off-topic detected for: '{stripped}'", flush=True)
            return QueryPlan(
                intent="off_topic",
                steps=[],
                visualizations=[],
                report_prompt=None,
            ), [{"name": "Intent Check", "status": "completed", "detail": "Greeting or too-short input detected — skipping AI.", "elapsed_ms": 0}]

        # Fast path: an event ID anywhere in the sentence is deterministic, no LLM needed.
        id_match = EVENT_ID_IN_TEXT.search(stripped)
        if id_match:
            ctx = QueryContext(
                user_input=stripped,
                intent_category="detail",
                query_text=id_match.group(0),
                confidence="high",
            )
            t0 = time.time()
            plan = self._rule_based_plan(ctx)
            if plan:
                step_types = " → ".join(s.type for s in plan.steps)
                return plan, [{
                    "name": "Event ID Match",
                    "status": "completed",
                    "detail": f"Event ID '{id_match.group(0)}' found in the query | Tools: {step_types}",
                    "elapsed_ms": round((time.time() - t0) * 1000, 1),
                }]

        # Phase 1: Context Extraction (Ollama)
        t0 = time.time()
        ctx = await self.router.extract_context(stripped)
        ctx.user_input = stripped  # Preserve original query
        t_router = round((time.time() - t0) * 1000, 1)

        router_label, router_dates = ctx.intent_category, (ctx.date_start, ctx.date_end)

        # Phase 1b: deterministic, validated dates (overrides the router's dates)
        self._resolve_dates(ctx, stripped)

        # Phase 1b': the router's label must agree with the user's words.
        #  * "detail" without an event ID: real IDs never reach the router (fast path above).
        #    The router called "Were there more protests in Texas in October than in September?" detail.
        #  * "brief" with no briefing words: "news about the march on Washington DC" became a
        #    one-day brief for yesterday.
        #  * a briefing word and a single day, labelled search, or overview with no place (which
        #    cannot run as an overview): "give me a recap of 2024-11-05" got both labels.
        if ctx.intent_category == "detail":
            ctx.intent_category = "search"
        elif ctx.intent_category == "brief" and not _BRIEF_RE.search(stripped):
            ctx.intent_category = "search"
        elif ((ctx.intent_category == "search" or (ctx.intent_category == "overview" and not ctx.location))
              and _BRIEF_RE.search(stripped) and ctx.date_start and ctx.date_start == ctx.date_end):
            ctx.intent_category = "brief"
        if ctx.intent_category == "search" and _HOT_RE.search(stripped):
            # "biggest news on 2024-07-04": the router said brief (no briefing word, so search
            # above) or search; the words ask for the most-covered events (held-out v2).
            ctx.intent_category = "hot"

        # Phase 1c: "how has California been this month" asks about a region as a whole.
        # The 3B router labels it brief or search depending on the state name, and for
        # California it also dropped the location.
        if ctx.intent_category in ("search", "brief") and _OVERVIEW_RE.search(stripped):
            self._recover_location(ctx)
            if ctx.location:
                ctx.intent_category = "overview"
        elif ctx.intent_category == "overview" and not ctx.location:
            # Right label, place dropped: "overview of British Columbia this year" (held-out v2).
            self._recover_location(ctx)

        routing_confidence, routing_reasons = self._routing_confidence(ctx, router_label, router_dates)
        if isinstance(self.router, ClaudeRouter) and ctx.router not in (self.router.model, "rules"):
            routing_reasons.append(f"Claude router unavailable, {ctx.router} used")
            if routing_confidence == "high":
                routing_confidence = "medium"

        detail_parts = [f"intent='{ctx.intent_category}'"]
        if ctx.location:
            detail_parts.append(f"loc='{ctx.location}'")
        if ctx.date_start:
            detail_parts.append(f"date={ctx.date_start} to {ctx.date_end} [{ctx.date_source}, {ctx.date_status}]")
        elif ctx.date_status == "invalid":
            detail_parts.append("date=invalid, not used")
        if ctx.event_type:
            detail_parts.append(f"type='{ctx.event_type}'")
        if ctx.query_text:
            detail_parts.append(f"text='{ctx.query_text}'")
        
        print(f"[Planner] Context: {', '.join(detail_parts)} | confidence={ctx.confidence} in {t_router}ms", flush=True)
        phases.append({
            "name": "Context Extraction",
            "status": "completed",
            "detail": f"{ctx.router or 'Router'} extracted: {', '.join(detail_parts)} ({ctx.confidence} confidence)",
            "elapsed_ms": t_router,
        })
        phases.append({
            "name": "Routing Check",
            "status": "completed",
            "detail": f"routing confidence {routing_confidence}" + (f": {'; '.join(routing_reasons)}" if routing_reasons else ""),
            "elapsed_ms": 0,
        })

        if ctx.intent_category == "off_topic":
            return QueryPlan(
                intent="off_topic",
                steps=[],
                visualizations=[],
                report_prompt=None,
            ), phases

        # Phase 2a: period comparison ("did X increase this month?"): count two complete
        # periods and compare, rather than summarising a top-N sample. Decided from the
        # user's words, not the router's label: the router called "Did protests increase
        # in Canada in March compared with February?" a daily brief.
        comparison = resolve_comparison_periods(stripped) if ctx.intent_category != "detail" else None
        if comparison:
            # "Did protests increase in January?" compares with December 2023, which is not in
            # the dataset: the count there is unknown, not zero ("December 2023 had none" was
            # the verdict). Compare only periods that overlap the data; cut partial ones.
            earlier, later = comparison
            earlier_in, later_in = clip_to_dataset(earlier), clip_to_dataset(later)
            if earlier_in is None or later_in is None:
                missing = earlier if earlier_in is None else later
                kept = later_in or earlier_in
                ctx.date_note = (
                    f"The dataset covers {DEFAULT_DATA_START} to {DEFAULT_DATA_END}, so {later.label} cannot be "
                    f"compared with {earlier.label}: there is no data for {missing.label}"
                    + (f". Showing {kept.label} only." if kept else ".")
                )
                if kept:
                    ctx.date_start, ctx.date_end = kept.start_iso, kept.end_iso
                comparison = None
            else:
                comparison = (earlier_in, later_in)
        if comparison:
            t0 = time.time()
            compare_plan = self._comparison_plan(ctx, comparison)
            compare_plan.routing_confidence = routing_confidence
            t_plan = round((time.time() - t0) * 1000, 1)
            phases.append({
                "name": "Comparison Planning",
                "status": "completed",
                "detail": f"Two periods resolved: {comparison[0].label} vs {comparison[1].label} | Tools: compare_periods",
                "elapsed_ms": t_plan,
            })
            return compare_plan, phases

        # Phase 2: Rule-Based Plan Generation — direct tool mapping, no LLM for simple queries
        t0 = time.time()
        fast_plan = self._rule_based_plan(ctx)
        if fast_plan:
            fast_plan.routing_confidence = routing_confidence
            if ctx.date_note and not fast_plan.notice:
                fast_plan.notice = ctx.date_note
                window = self._queried_window(fast_plan) if ctx.date_status == "invalid" else None
                if window:
                    fast_plan.notice += f" Showing {window} instead."
            t_plan = round((time.time() - t0) * 1000, 1)
            step_types = ' → '.join(s.type for s in fast_plan.steps)
            detail = f"Matched '{fast_plan.intent}' | Tools: {step_types}"
            print(f"[Planner] Rule-based plan: {fast_plan.intent} with {len(fast_plan.steps)} steps in {t_plan}ms", flush=True)
            phases.append({"name": "Rule-Based Planning", "status": "completed", "detail": detail, "elapsed_ms": t_plan})
            return fast_plan, phases
        
        # Fallback: remote LLM for truly ambiguous queries
        print(f"[Planner] Rule base couldn't match, falling back to remote LLM", flush=True)
        plan = await self._llm_plan(stripped, ctx)
        plan.routing_confidence = "low"  # the rules could not plan it
        t_plan = round((time.time() - t0) * 1000, 1)
        step_types = ' → '.join(s.type for s in plan.steps)
        detail = f"Remote LLM generated plan | Tools: {step_types}"
        phases.append({"name": "AI Planning", "status": "completed", "detail": detail, "elapsed_ms": t_plan})
        return plan, phases


# ---------------------------------------------------------------------------
# Report Generator
# ---------------------------------------------------------------------------

REPORT_SYSTEM_PROMPT = """You are a GDELT event narrative analyst. Weave event data into a coherent story with a clear narrative arc.

Rules:
- Output plain text / markdown. Do NOT use JSON.
- 2-4 short paragraphs max.
- Tell a story: context → key events → implications or connections.
- Cite specific dates, locations, actors, and article counts from the data.
- If data is empty or sparse, say so directly.
- Only state totals, percentages, increases or decreases that appear verbatim in a PERIOD COMPARISON section. A list of top events is a sample: never turn it into a count or a trend.
- Without a PERIOD COMPARISON section, do not describe change over time at all, with or without numbers ("coverage rose toward the end of the month", "activity picked up"): the events are chosen by article count, so their dates say nothing about trends.
- No preamble like "Here is the analysis". Start immediately with the story."""


class ReportGenerator:
    """Generates narrative reports from structured event data.
    
    Pre-processes raw step results into a clean narrative format before sending to LLM.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.llm = build_llm(config)

    def _get_response_text(self, response) -> str:
        """Extract text from an LLM response (falls back to reasoning_content for reasoning models)."""
        text = ""
        if hasattr(response, "content") and response.content:
            text = response.content.strip()
        if not text and hasattr(response, "additional_kwargs"):
            text = response.additional_kwargs.get("reasoning_content", "") or ""
            if text:
                text = text.strip()
        if not text and hasattr(response, "response_metadata"):
            text = response.response_metadata.get("reasoning_content", "") or ""
            if text:
                text = text.strip()
        return text

    @staticmethod
    def _format_event(evt: Dict[str, Any], is_primary: bool = False) -> str:
        """Format a single event into a concise narrative string."""
        parts = []
        prefix = "PRIMARY: " if is_primary else "- "
        
        # Date
        date = evt.get("SQLDATE") or evt.get("date", "unknown date")
        parts.append(f"Date: {date}")
        
        # Location
        loc = evt.get("ActionGeo_FullName") or evt.get("location_name") or evt.get("ActionGeo_CountryCode", "unknown")
        parts.append(f"Location: {loc}")
        
        # Actors
        actor1 = evt.get("Actor1Name") or evt.get("actor1_name", "")
        actor2 = evt.get("Actor2Name") or evt.get("actor2_name", "")
        if actor1 or actor2:
            actors = f"{actor1 or '?'} vs {actor2 or '?'}"
            parts.append(f"Actors: {actors}")
        
        # Headline / title
        headline = evt.get("headline")
        if not headline and (actor1 or actor2):
            headline = f"{actor1 or 'Unknown'} vs {actor2 or 'Unknown'}"
        if headline:
            parts.append(f"Title: {headline}")
        
        # Summary
        summary = evt.get("summary", "")
        if summary:
            summary = summary[:250] + "..." if len(summary) > 250 else summary
            parts.append(f"Summary: {summary}")
        
        # Articles (signal of importance)
        articles = evt.get("NumArticles") or evt.get("num_articles")
        if articles:
            parts.append(f"Articles: {articles}")
        
        # Goldstein scale (conflict/cooperation)
        goldstein = evt.get("GoldsteinScale") or evt.get("goldstein_scale")
        if goldstein is not None:
            tone = "conflict" if goldstein < -5 else "cooperation" if goldstein > 5 else "neutral"
            parts.append(f"Tone: {tone} ({goldstein})")
        
        # Event type label
        evt_type = evt.get("event_type_label") or evt.get("event_type")
        if evt_type:
            parts.append(f"Type: {evt_type}")
        
        return prefix + " | ".join(parts)

    def _format_data_for_report(self, data: Dict[str, Any]) -> str:
        """Pre-process raw step results into a clean narrative input."""
        sections = []
        total_events = 0
        
        for key, item in data.items():
            step_type = item.get("type", "unknown")
            step_data = item.get("data")
            
            if step_type == "event_detail" and step_data:
                sections.append("=== PRIMARY EVENT ===")
                if isinstance(step_data, dict):
                    sections.append(self._format_event(step_data, is_primary=True))
                    # Include raw event_data if available
                    raw = step_data.get("event_data")
                    if raw and isinstance(raw, dict):
                        sections.append(self._format_event(raw, is_primary=True))
                else:
                    sections.append(str(step_data))
                    
            elif step_type == "similar_events" and step_data:
                events = step_data if isinstance(step_data, list) else []
                sections.append(f"=== {len(events)} RELATED EVENTS ===")
                for evt in events[:8]:  # Cap at 8
                    sections.append(self._format_event(evt))
                    total_events += 1
                    
            elif step_type == "compare_periods" and step_data and isinstance(step_data, dict):
                sections.append("=== PERIOD COMPARISON (computed counts, quote exactly) ===")
                sections.append(f"Verdict: {step_data.get('verdict')}")
                for key in ("earlier", "later"):
                    p = step_data.get(key) or {}
                    sections.append(
                        f"{p.get('label')}: {p.get('event_count'):,} events over {p.get('days')} days "
                        f"({p.get('events_per_day')} per day), {p.get('start')} to {p.get('end')}"
                    )
                pct = step_data.get("percent_change_per_day")
                if pct is not None:
                    sections.append(f"Change in events per day: {pct:+.1f}%")
                filters = step_data.get("filters") or {}
                sections.append(f"Filters: location={filters.get('location')}, event_type={filters.get('event_type')}")
                for caveat in step_data.get("caveats", []):
                    sections.append(f"Caveat: {caveat}")

            elif step_type in ("events", "top_events", "hot_events") and step_data:
                events = step_data if isinstance(step_data, list) else []
                shown = events[:10]  # Cap at 10
                # These tools return the top-N events by article count, not every matching
                # event. The header used to say "TOP 18" above a list of 10; it now says what
                # is listed, and that a sample supports neither totals nor trends over time.
                sections.append(
                    f"=== {len(shown)} OF THE TOP {len(events)} EVENTS BY ARTICLE COUNT (the most-covered "
                    f"{len(shown)} are listed; a sample, not a total count and not a time series: do not state "
                    "totals, and do not say activity or coverage rose, fell or grew over time) ==="
                )
                for evt in shown:
                    sections.append(self._format_event(evt))
                    total_events += 1
                    
            elif step_type == "regional_overview" and step_data:
                sections.append("=== REGIONAL SITUATION ===")
                if isinstance(step_data, dict):
                    summary = step_data.get("summary", {})
                    if summary:
                        sections.append(f"Summary: {json.dumps(summary, default=str)}")
                    hot = step_data.get("hot_events", [])
                    if hot:
                        sections.append(f"Hot events ({len(hot)}):")
                        for evt in hot[:5]:
                            sections.append(self._format_event(evt))
                else:
                    sections.append(str(step_data))
                    
            elif step_type == "daily_brief" and step_data:
                sections.append("=== DAILY BRIEF ===")
                if isinstance(step_data, dict):
                    total = step_data.get("total_events")
                    if total:
                        sections.append(f"Total events: {total}")
                    conflict = step_data.get("conflict_events")
                    if conflict is not None:
                        sections.append(f"Conflict events: {conflict}")
                    avg_tone = step_data.get("avg_tone")
                    if avg_tone is not None:
                        sections.append(f"Avg tone: {avg_tone}")
                else:
                    sections.append(str(step_data))
        
        result = "\n\n".join(sections)
        # Hard cap at ~5000 chars to stay within token budget
        if len(result) > 5000:
            result = result[:4800] + "\n\n... [additional events omitted]"
        return result

    async def generate(self, data: Dict[str, Any], prompt: Optional[str] = None) -> ReportResult:
        """Generate a narrative report from query results."""
        # Pre-process data into narrative format
        narrative_data = self._format_data_for_report(data)
        
        if not narrative_data.strip() or narrative_data.strip() == "=== 0 EVENTS FOUND ===":
            return ReportResult(
                summary="No events were found for this query. Try broadening your search (e.g., removing location filters or expanding the date range).",
                key_findings=[],
            )

        user_prompt = prompt or "Tell the story of these events. Connect them with context and implications."

        messages = [
            SystemMessage(content=REPORT_SYSTEM_PROMPT),
            HumanMessage(content=f"{user_prompt}\n\nEvent Data:\n{narrative_data}\n\nWrite the story:"),
        ]

        try:
            response = await asyncio.wait_for(self.llm.ainvoke(messages), timeout=120.0)
            text = self._get_response_text(response)

            # Clean up markdown code blocks if any
            text = re.sub(r'^```.*?\n', '', text, flags=re.DOTALL)
            text = re.sub(r'\n```$', '', text)

            if not text:
                return ReportResult(
                    summary="No report content was generated.",
                    key_findings=[],
                )

            # Split into summary + bullet findings
            lines = [l.strip() for l in text.split('\n') if l.strip()]
            summary_lines = []
            findings = []
            in_findings = False
            for line in lines:
                if line.lower().startswith(('key finding', 'findings', 'highlights', '- ')):
                    in_findings = True
                if in_findings and (line.startswith('- ') or line.startswith('* ')):
                    findings.append(line[2:].strip())
                elif in_findings:
                    findings.append(line)
                else:
                    summary_lines.append(line)

            summary = '\n'.join(summary_lines) if summary_lines else text
            if len(summary) > 4000:
                summary = summary[:4000] + "..."

            print(f"[ReportGenerator] Generated report: {len(summary)} chars summary, {len(findings)} findings", flush=True)
            return ReportResult(summary=summary, key_findings=findings)

        except asyncio.TimeoutError:
            print("[ReportGenerator] LLM timeout after 120s", flush=True)
            return ReportResult(
                summary="AI report generation timed out. The event data is still available above.",
                key_findings=[],
            )
        except Exception as e:
            print(f"[ReportGenerator] Failed: {e}", flush=True)
            return ReportResult(
                summary="Unable to generate AI report at this time. The analysis data is still available above.",
                key_findings=[],
            )
